server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: helpdesk
  flayway:
    anable: true
    baseline-on-migrate: false
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

app:
  path:
    files: /Users/yhugo/Desktop/Arquivos/

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key



